### ISSUE TITLE
unable to run deploy script

### ISSUE THREAD

**Issue by sirpy** [Mean-Finance/uniswap-v3-oracle#14]
There seems to be an issue importing from other packages
The first issue is importing StaticOracle from @typedchain
If I simply import it from the artifacts output json file it works just fine.
But then there's the second issue of importing `import { deployThroughDeterministicFactory } from '@mean-finance/deterministic-factory/utils/deployment';

The errors I get are related to commonjs/module issue
```
An unexpected error occurred:

Error: ERROR processing skip func of /Users/hadar/workspace/uniswap-v3-oracle/deploy/001_deploy.ts:
/Users/hadar/workspace/uniswap-v3-oracle/typechained/factories/node_modules/index.ts:4
export * as uniswap from "./@uniswap";
^^^^^^

SyntaxError: Unexpected token 'export'
    at compileFunction (<anonymous>)
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/hadar/workspace/uniswap-v3-oracle/node_modules/ts-node/src/index.ts:1445:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at DeploymentsManager.executeDeployScripts (/Users/hadar/workspace/uniswap-v3-oracle/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1107:15)
    at DeploymentsManager.runDeploy (/Users/hadar/workspace/uniswap-v3-oracle/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1059:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SimpleTaskDefinition.action (/Users/hadar/workspace/uniswap-v3-oracle/node_modules/hardhat-deploy/src/index.ts:438:5)
    at async Environment._runTaskDefinition (/Users/hadar/workspace/uniswap-v3-oracle/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:14)
    at async Environment.run (/Users/hadar/workspace/uniswap-v3-oracle/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:14)
    at async SimpleTaskDefinition.action (/Users/hadar/workspace/uniswap-v3-oracle/node_modules/hardhat-deploy/src/index.ts:584:32)
    at async Environment._runTaskDefinition (/Users/hadar/workspace/uniswap-v3-oracle/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:14)
    at async Environment.run (/Users/hadar/workspace/uniswap-v3-oracle/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:14)
    at async SimpleTaskDefinition.action (/Users/hadar/workspace/uniswap-v3-oracle/node_modules/hardhat-deploy/src/index.ts:669:5)
```

**Comment by sirpy** [comment]
this can be solved by adding the following to tsconfig
```
{
"ts-node": {
    "ignore": ["/node_modules/@mean-finance", "@typechained"]
  },
...
}
```

**Comment by 0xsambugs** [comment]
Thanks for pointing this out @sirpy , and for providing a workaround also! We'll take a look 🫡
